version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      ServerIP: "${ip:-0.0.0.0}"
      WEBPASSWORD: 12345678aA
      # DNS1: 8.8.8.8
      # DNS2: 1.1.1.1
      # DNS3: 9.9.9.9
    volumes:
      - './data/pihole/:/etc/pihole/'
      - './data/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter
    hostname: pihole-exporter
    ports:
      - 9617:9617
    expose:
      - 9617
    environment:
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PORT: 80
      PIHOLE_PASSWORD: 12345678aA
      INTERVAL: 30s
      PORT: 9617
    restart: always
  speedtest-exporter:
    container_name: speedtest-exporter
    image: miguelndecarvalho/speedtest-exporter
    # environment:
    #   - SPEEDTEST_PORT=8080 #optional
    #   - SPEEDTEST_SERVER=40571 #optional
    ports:
      - 9798:9798
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    restart: unless-stopped
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - './config/prometheus/:/etc/prometheus'